import * as path from 'path';
import * as fs from 'fs';

/**
 * Project Detector - Handles project root discovery and data directory resolution.
 * Inspired by patterns in code-review-graph.
 */
export class ProjectDetector {
  /**
   * Find the project root by walking up from startPath.
   * Looks for pubspec.yaml (priority) or .git markers.
   */
  static findProjectRoot(startPath: string = process.cwd()): string {
    // 1. Check environment variable override
    const envOverride = process.env.FLUTTER_PROJECT_PATH;
    if (envOverride && fs.existsSync(envOverride)) {
      return path.resolve(envOverride);
    }

    let current = path.resolve(startPath);
    const root = path.parse(current).root;

    while (current !== root) {
      // Priority: pubspec.yaml (definitely a Flutter project)
      if (fs.existsSync(path.join(current, 'pubspec.yaml'))) {
        return current;
      }
      
      // Secondary: .git (repository root)
      if (fs.existsSync(path.join(current, '.git'))) {
        return current;
      }

      current = path.dirname(current);
    }

    return startPath; // Fallback to current path
  }

  /**
   * Get the data directory for the project.
   * Priority:
   * 1. FLUTTER_EXPLORER_DATA_DIR env var
   * 2. <repo_root>/.flutter-explorer/
   */
  static getDataDir(projectRoot: string): string {
    const envOverride = process.env.FLUTTER_EXPLORER_DATA_DIR;
    if (envOverride) {
      const dataDir = path.resolve(envOverride);
      if (!fs.existsSync(dataDir)) {
        fs.mkdirSync(dataDir, { recursive: true });
      }
      return dataDir;
    }

    const dataDir = path.join(projectRoot, '.flutter-explorer');
    if (!fs.existsSync(dataDir)) {
      fs.mkdirSync(dataDir, { recursive: true });
    }

    // Add a .gitignore to the data dir to prevent accidental commits
    const gitignorePath = path.join(dataDir, '.gitignore');
    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, '# Auto-generated by Flutter Explorer - do not commit database files.\n*\n');
    }

    return dataDir;
  }

  /**
   * Get the SQLite database path.
   */
  static getDbPath(projectRoot: string): string {
    const dataDir = this.getDataDir(projectRoot);
    return path.join(dataDir, 'flutter-explorer.db');
  }

  /**
   * Determine the project type based on the presence of key files.
   */
  static getProjectType(projectRoot: string): 'flutter' | 'ts' | 'android' | 'unknown' {
    if (fs.existsSync(path.join(projectRoot, 'pubspec.yaml'))) {
      return 'flutter';
    }
    if (fs.existsSync(path.join(projectRoot, 'package.json')) || fs.existsSync(path.join(projectRoot, 'tsconfig.json'))) {
      return 'ts';
    }
    if (fs.existsSync(path.join(projectRoot, 'build.gradle')) || fs.existsSync(path.join(projectRoot, 'settings.gradle')) || fs.existsSync(path.join(projectRoot, 'build.gradle.kts'))) {
      return 'android';
    }
    return 'unknown';
  }
}
